---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - JAsfBM5A9Tie4ihJ91nBfLE+YQ6QUSgPUqi75HgWUA1+CcLfJRmH7hI06+fpj+nL8DmRE
          OrAQ4zVo9UX3C9Nsx8V1aRGiV0JVp8kQeTl+JX1YnH1jDRrWMUyjijhIU0606xHFC/mqK
          BwaapDolbJ9qf/KyZf95p4D83Asm6p9Fs+Bxe39GPbow98tu0zCMDjgY3ZHwCvL2atReL
          iVLREvR/hfcGZlOgmhOSV9cqglIW3VDdvIS3OXRSezGKiRP7mNpIM5CNfwOMN9ptriWLL
          jIlKMSt+lO+5CchZUXTU4Ka6Lc+65JLirzJxmTCefkomVyFjrg07V9GQAXHW8Z81TjCHA
          0wZVxPdouZU1k89pCwsrO51u+Ti8KtkJgsBBeOiTQoBhUH7W3tldxk0tf0u5dS6tfbfKt
          9AjVTacbLGqJMXNOgEQn2Zgl5/IcSGWY3mTlTKfOBv0TK5l8ATmmMtuHpFTkcq+lt1hxY
          4ODmMkP9waTb46OaI4aMVwfwWQQnlfRRMKbxH1lQONNyomH2OVEeUkaFx8u13Dx3bNkIc
          v67ut7/VSN7YMSPwz/vntpRxhEkx+A2SnKueDHvyn5J+3RLYnT1KeKZ5CWkPjGsqdgo3K
          jn0ELHJsqUvP+NHiz3cdi32vnBl/o8Fu9u5SwvRJV97Nj/6eXlRAqckAj9kTMg=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

- semaphore:
    name: semaphore-testbed
    max: 1

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    cleanup-run: playbooks/managerless/cleanup.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- job:
    name: testbed-deploy
    nodeset: ubuntu-jammy
    pre-run: playbooks/pre.yml
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    cleanup-run: playbooks/cleanup.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-default
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed

- job:
    name: testbed-deploy-post
    nodeset: ubuntu-jammy
    pre-run: playbooks/pre.yml
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    cleanup-run: playbooks/cleanup.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-default
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
    check-post:
      jobs:
        - testbed-deploy
    post:
      jobs:
        - testbed-deploy-post
    periodic-hourly-otc:
      jobs:
        # - ansible-lint
        - flake8
#        - testbed-deploy-managerless
#        - python-black
#        - yamllint
