---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - rAaXWCpcQ7w9l6JMtyCdB80OHrbIkhASOvA75STQe6FgghD3GTCz0zfIXBsxmXtdItKBq
          0sVhhWoQ+06tpmUfcnjHbYYAepeeI/sBkbNOoMxPWvhG3em0Qo2kkHcsD12pzMhZckQH1
          tpPRgIJbiX+Xx7XSOPg1c0ZwKXT7cisF4dlVtjqrgSGdD2d/uBH242YZQFnOwxSovlCgw
          XeHZjR32BhuZ4ru7uV9YNSzqmMNyYvfbQs13ysD9ZC94IwTLTIRVQjfrajZQqFpoR5g30
          x6cM5iMuSOMfNOLJbvJ/nMaKwBYN913lpSiKYBfj93lbwzqWOAVED1JnM10oQPawSKTN5
          5RvrskS/V/+CzYY9GggNogJCm4i3e/e/lii0Iu9b1eFiiDitjlMeQTog5hTJqSYVz2rwg
          +FWInoeTA8cSruqIbI94sZ2sLc65We4/ozq3e+M8NRjK34Vz0J4QHAaPXUKogliOUH5Xv
          jtkqU1EUFwCR2/uwALLjBtTZ4h59J0MZQ+v08ibqbt+JzQoYdLOXNn4apxJhY+acn4d7a
          G0LMKaO+TlxHTc5h3T9ycnfVXxOE5FDTDmKqpeNPO7nmGZRiwn3ztiNkRUcx6y/IvyMQ0
          GEXGvBNALJWYvDIb5q9RkbTPnLftxkKuKV15PUyGAmZl26OXlhKWQdgowN28nA=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    cleanup-run: playbooks/managerless/cleanup.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
#        - ansible-lint
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-hourly-otc:
      jobs:
        - ansible-lint
        - flake8
#        - testbed-deploy-managerless
#        - python-black
#        - yamllint
