---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - aU9JGhB1/WFHsi1htqkl+jDYztrJh5SHnu6BtGn9+8wxDtXdMwGrM9R/IdmAmXUMAcrGS
          uGFA+C4B9Ywkxsbm3U8uzhD9CExB8fucKsJJPWHjf9MYtyKB4hEfgF/xtB1d7QyC3/3L4
          mb0S0MnbZcGFIeY+iSbPfNoBedfPUzml6u1lSKkaS9Lp1JNSuhtuxnM6ssHHaMTsRKwl9
          2jLfG6efPrrMs7WxHhc8zFSPBQgeP/DshkU8aM8sUeJuNxQ+slJUh+5eQiRanDlWAdTrP
          utH5eNiDRehC8+LGwf7jVw+tupapAuDKNRhSkHcIW9kGMNi/TSzW1zYrbdNCPUCoC3xKZ
          ruHsiqCWCuDa2DqeFlIRI9i3Viltp8UFs7Ntz9awmChwCAv/tjSAdbx5iprJSQ48Rs4pZ
          w0Yvn9KZiNMaWnYscCUlLE5gPmdLqL5UbxeA0R1SYIZPX0OvuR/odsRw/29kDnb1TSxdP
          FvmWsDQssuBZuwfksxPygOb/hzmA3VGyaD8NSKj0wE92cunsNbUxUvyTBs7yM+cneKv3X
          zTTYbdityzieUxK4AIVGooe3yYsIKAnvDoLrGiMwYCbW2zVd5RhWxvbVYQWWy/UvbE7My
          YhrCNtnWiGbapxcmOJlipWiN1eqfi2WgK69QkDsQgleNKq31uOiRqrpdib033o=

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-half-hourly-otc:
      jobs:
        - testbed-deploy-managerless
        - ansible-lint
        - yamllint
        - flake8
