---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - NKkIlmAdinWbRT4uPfVkYclu18Ylapc9AqxYxuU3/wv5BEshpxTOc4MXhW0vCwhmc4r3/
          b/xRP5iNv6Z06lSoNzfWmOvrYM6JUd31s2AXbwO2jjkQ2pAmq4Kj0IT5rtnMFpK4avPsB
          +1Q/b2PIuvVWmkq4CbyWDZgJDmH0UhisLpGUVZ2TiPAWc5AB9V1814jfI/nYaVzwvBfBB
          Uoh3nlhvhoPVAiCxwnX+htaEeXFI1+dN7p23EZglJKDNeEaT61obt36iGbo9Y833UVW4F
          RKDfcg7YygtqWvGzLHwuxVYPcCnZuLtlU4u8F6R8RN//PNDtcMvsb1uAjHwl0LluLj93q
          LLriOWb/qvpZKqAOHG0YfaYlEKZrWXXLc8zfA/iFzkWy/iDzRQk61fcEBoJ98JSVXqhDt
          L0WQ0Rv0Y2/jAW+eOJW0HOv+NDXHHlVuhxEPBXeNurauGoy+DeoL8UEh3LakvNkr59M+H
          194xrSzmu4LPpmN0DUJ2ddb3An9Px03mHZV+IRL2GT0t/nT3bpo4Nvt6QpNjNzjYfcCOI
          RIazEWyOABbaACx7hwCJeiivtnl/GSu12lkCInHhVZS4l64Ljl47qCrpKBU93EoNwfFjS
          evIXLpLR27vjKD/cpwuMefRRRXw3xSK9F863wLqvlvMPY/7WIY9JjBpcDhTtpU=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - ansible-lint
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-hourly-otc:
      jobs:
        - ansible-lint
        - flake8
#        - testbed-deploy-managerless
#        - python-black
#        - yamllint
