---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - C1cOatGA837DORobPx+rYJCexmOpLmsPnTVlbuQIXCn/lnBSx3VLI4Tdtw6NxOau6Q2gg
          TFmp6L/yYkc3KSdKRgakL2mMdPk7NkDTIU+qyF7l+2eBeq/kzaxXMrgTJ4/cBEpZZSTG7
          zybKIcWIR5r6rqqeQFO3q9i2C3i9XKimgvhnb2J/UYbCQj4VLaxq3+jCuL66oc+sPED9w
          CSa1+/8S0WK0HhRWTdfdVYyiS0EdDpVEOfffgHV54qReZAqA3hetSrOukHisMJbMeYyBV
          wJcZEquHOUls0Pz8yOhebazFAsybNODtr9NPdjfLniKccl6p+VWQd9zrListPkoxATsvo
          xhmT4TnFFMriTRtr5gLP/+ikfu47gWS6KNAmqse8Ek/ily2f9UJEoLlCtjRx+Z1ErVZED
          5wu6+TZJ5JWVBc/WyaTouIUUtuWgLmbHc7rA3plE5FR2onfWPsH1oMgZwhioZM3zySvvT
          FExr+M4PA7Y4PhwFpW17XQzljaXXTbrysefqOzYAY8BuIhLWFOMAdjCcAsxisE4PBm3Gq
          B46x3VKlfS6YWil3jTy7ChRaHHIfE7A9FwDhTlH66ikgal5IJWo6ph4WiGlynhT735jK8
          9CSiKzZrqSbeVpeHHzCuw6noqHk93y1qjbknStd5cHLCzxh2Il8ebHb+z9bI8w=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    cleanup-run: playbooks/managerless/cleanup.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - ansible-lint
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-hourly-otc:
      jobs:
        - ansible-lint
        - flake8
#        - testbed-deploy-managerless
#        - python-black
#        - yamllint
