---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - BiqU95oqt1m2M9nGaxVDqUySzeNSqH5QZH7+CtbFGsWFJ1BjuJ65ZXtnVPdTdXK2HyMmv
          8FvNDKvc+Mt3VbwZ0bhK4eXgGov+pO2MLopr9EURumCAcDAFgStqiN32FYxWoEe65b7gh
          o5++8pYLJLqBHiLQaKKgYkiA0CGygLngswQzzUWzih88oHwV4Aidc3wwlobGopeB9g9QB
          31I/G3bNZqzEzT6sHFfGjESOrMqAq/+c2DSpkQezSfDwH9b2eEPaGGY9O7F6Oc+zhB/7g
          v/15HKePLTbxfmqxRHBPqhSh2yO71PzHckAli59EsBpJpvOsTbOzQXe6m0a4cDoXZOKUE
          WJmp6GcwJofDEcfviPAdorfMEFOVRmGgSl8HzTCmr81NhgLzeh+LJttid60v48xQvPbnc
          WYT9QBOhXlUbgWkNGZ1DPFh6eY1ygKqagu1wdBiSFVrJE50lqRSI7KMB1XMhlOJDs4KFY
          piN8LAKlRMlQiZXsZ3T3iHWBz2dbWYBmHCSsleJqjVJoEjZ+ysB1bgXHGzvktig2NdpoB
          QmSsfeU1HlVXB1p1HCdNrZScTT2bObPIzpnbzNyQsA8NAQxaerl1wUzIkMZw5rTMlZfsF
          ZxYqNQ8bWHvC2lOoZ3QRy1JpHA/z9hp4udDUoQL6BeqqAc07soskhHxBUiUTYw=
        - jtzV0DTIEDJC/1v62Wj4qVLwWNqxWU/pxUHURK/IvMvdkfeISnUkh0+WztKaD+TmrukpQ
          RnauWkRL0J40d9NfZrPfzFKGtMSIamw8Ky+NJnkLVqOf1LSH9O80h83YTOwXYTc5/Tz5w
          nMV2ac+mg6bwo7+5OiORYbwzanAOSzX7NAS69jX/uEBgZO+JQx86DKX+U7oDuaPD+HsMP
          WwqYzNadIFo2l0GOmMif3P+nfwfbykn+gDDAUwz8QATCQHfImwrxnxj27TX7og4rou617
          +38dIUB8GfmK37x4qgWSBFZLKwmYssrZpqr+vWrTcTvXixfL1fk+vkLxwZS1u9gW6nbeT
          idKWSNt8U5jRvmC/tHlJ9kcAP3opWkJ4EJJ9o21noqTLBdbkARYSRKbJYr0jrmS4TzhLv
          NSRegrlWiksYGLhBmHjlsGo10ZgaAZEarhwPklVG0bFxxGDOf4csodPh29mKLy+RgYSEb
          EOy7cQR+ntKCnmYXr9jw+B3OHgoTpc2m8i+RQxOxH7RTVEDbWlsln+egR/Qghd0lAu7XU
          Bg5oUx0YSyfw5JX6FgNSByUiz9Soo6fEmAJ7Y+yV53Dt+G+Zrv1ygbtmCtJQLiCt/enka
          6iN3RzLbS/qC29zQCtpYzslGUzAxkHH5C6/WC3UX9/LHZmdHVd87IRJ86q3LV8=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - ansible-lint
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-hourly-otc:
      jobs:
        - ansible-lint
        - flake8
#        - testbed-deploy-managerless
#        - python-black
#        - yamllint
