---
- name: Cleanup play
  hosts: all

  vars_files:
    - vars/mappings.yml
    - vars/repositories.yml

  vars:
    basepath: "{{ ansible_user_dir }}/src/{{ repositories['testbed']['path'] }}"

  tasks:
    - name: debug
      ansible.builtin.debug:
        msg:
          groups_all: "{{ groups['all'] }}"
          hostvars_first: "{{ hostvars[groups['all'][0]] }}"
          nodepool_exists: "{{ 'nodepool' in hostvars[groups['all'][0]] }}"
          nodepool_label: "{{ hostvars[groups['all'][0]].get('nodepool', {}).get('label', 'undefined') }}"

    - name: Set cloud_env fact (Zuul deployment)
      ansible.builtin.set_fact:
        cloud: "{{ cloud_envs[hostvars[groups['all'][0]]['nodepool']['label']] }}"
      when: "'nodepool' in hostvars[groups['all'][0]]"

    - name: Set cloud fact (local deployment)
      ansible.builtin.set_fact:
        cloud: "{{ testbed_cloud | default('ci') }}"
      when: "'nodepool' not in hostvars[groups['all'][0]]"

    - name: Clean the cloud environment
      ansible.builtin.shell:
        cmd: |
          OS_CLOUD={{ cloud }} ~/venv/bin/python3 cleanup.py
        chdir: "{{ basepath }}/terraform/scripts"
      failed_when: false
      changed_when: true
